[package]
name = "open-lark"
version = "0.1.0"
edition = "2021"
authors = [
    "ZoOL <zhooul@gmail.com>"
]
readme = "README.md"
description = "Lark/Feishu Open API SDK(WIP)"
keywords = ["sdk", "feishu", "lark", "rest"]
categories = ["api-bindings"]
documentation = "https://docs.rs/open-lark"
repository = "https://github.com/foxzool/open-lark"
license = "MIT OR Apache-2.0"


[dependencies]
base64 = "0.22.1"
bytes = "1.6.0"
chrono = "0.4.38"
hmac = "0.12.1"
sha2 = "0.10.8"
lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
thiserror = "1.0.60"
log = "0.4.21"
url = { version = "2.5.0", features = ["serde"] }
ureq = { version = "2.9.7", features = ["json", "socks-proxy"] }
strum = "0.26.2"
strum_macros = "0.26.2"


[dev-dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.3"
uuid = { version = "1.8.0", features = ["v4"] }

[[example]]
name = "card_column_set"
path = "examples/card/column_set.rs"

[[example]]
name = "card_form_set"
path = "examples/card/form.rs"

[[example]]
name = "card_interactive"
path = "examples/card/interactive.rs"

[[example]]
name = "card_collapsible"
path = "examples/card/collapsible.rs"

[[example]]
name = "create_message"
path = "examples/api/im/v1/create_message.rs"

[[example]]
name = "list_message"
path = "examples/api/im/v1/list_message.rs"

[[example]]
name = "list_chat"
path = "examples/api/im/v1/list_chat.rs"
