[package]
name = "open-lark"
version = "0.0.2"
edition = "2021"
authors = [
    "ZoOL <zhooul@gmail.com>"
]
readme = "README.md"
description = "Lark/Feishu Open API SDK(WIP)"
keywords = ["sdk", "feishu", "lark", "rest"]
categories = ["api-bindings"]
repository = "https://github.com/foxzool/open-lark"
license = "MIT OR Apache-2.0"





[dependencies]


reqwest = { version = "0.12.3", features = ["json", "rustls-tls"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
log = "0.4.21"

[dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.37.0", features = ["full"] }

[[example]]
name = "custom_bot"
path = "examples/custom_bot.rs"
