[package]
name = "open-lark"
version = "0.0.4"
edition = "2021"
authors = [
    "ZoOL <zhooul@gmail.com>"
]
readme = "README.md"
description = "Lark/Feishu Open API SDK(WIP)"
keywords = ["sdk", "feishu", "lark", "rest"]
categories = ["api-bindings"]
repository = "https://github.com/foxzool/open-lark"
license = "MIT OR Apache-2.0"


[dependencies]

bytes = "1.6.0"
futures = "0.3.17"
reqwest = { version = "0.12.3", features = ["json", "rustls-tls", "multipart", "stream"] }
lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
thiserror = "1.0.60"
log = "0.4.21"
url = { version = "2.5.0", features = ["serde"] }
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = "0.1.15"

[dev-dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.3"
uuid = { version = "1.8.0", features = ["v4"] }


[[example]]
name = "create_message"
path = "examples/api/im/v1/create_message.rs"

[[example]]
name = "list_message"
path = "examples/api/im/v1/list_message.rs"

[[example]]
name = "list_chat"
path = "examples/api/im/v1/list_chat.rs"
